on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - uses: patrick91/setup-python@feature/poetry-caching
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry install
      - run: poetry run strawberry
